# version 01

print('01 first text version1 by Artem')
print('02 first text version1 by Artem')
print('03 first text version1 by Artem')
print('04 first text version1 by Artem')
print('05 first text version1 by Artem')
print('06 first text version1 by Artem')
print('07 first text version1 by Artem')
print('08 first text version1 by Artem')
print('09 first text version1 by Artem')
print('10 first text version1 by Artem')
print('11 first text version1 by Artem')
print('12 first text version1 by Artem')
print('13 first text version1 by Artem')
print('14 first text version1 by Artem')
print('15 first text version1 by Artem')
print('16 first text version1 by Artem')
print('17 first text version1 by Artem')
print('18 first text version1 by Artem')
print('19 first text version1 by Artem')
print('20 first text version1 by Artem')
